name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "usage of env"
        run: |
          out=$(python ./bin/test.py)
          echo $out
        env:
          QNAME: mmiya
