name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v3
      - name: Set environment variable
        id: generate_name
        run: echo "filename=my_value" >> $GITHUB_OUTPUT
      - name: run python script
        run: python ./bin/test.py
        env:
          QNAME: ${{ steps.generate_name.outputs.filename }}

