# Generic workflow with the same name, that will return true in any case similar to the non generic workflow.
# source: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: "Terraform PR"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  user-existence-check:
    name: "User Existence Check"
    runs-on: ubuntu-latest
    steps:
      - name: "输出默认环境变量"
        run: |
          echo "this is call function"
          
  call-workflow:
    uses: ./.github/workflows/other.yml

  job-2:
    name: "diergerenwu"
    runs-on: ubuntu-latest
    steps:
      - name: "输出"
        run: |
          echo "output something"

        
        


