# Generic workflow with the same name, that will return true in any case similar to the non generic workflow.
# source: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: "Terraform PR"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  user-existence-check:
    name: "User Existence Check"
    runs-on: ubuntu-latest
    steps:
      - name: "输出默认环境变量"
        run: |
          echo "$GITHUB_ACTION"
          echo "$GITHUB_ACTION_PATH" 
          echo "$GITHUB_ACTION_REPOSITORY" 
          echo "$GITHUB_ACTIONS" 
          echo "$GITHUB_ACTOR" 
          echo "$GITHUB_API_URL" 
          echo "$GITHUB_BASE_REF" 
          echo "$GITHUB_ENV" 
          echo "$GITHUB_EVENT_NAME" 
          echo "$GITHUB_EVENT_PATH" 
          echo "$GITHUB_GRAPHQL_URL" 
          echo "$GITHUB_HEAD_REF"
          echo "$GITHUB_JOB"
          echo "$GITHUB_PATH"
          echo "$GITHUB_REF"
          echo "$GITHUB_REF_NAME"
          echo "$GITHUB_REPOSITORY"
          echo "$GITHUB_STEP_SUMMARY"
          echo "$GITHUB_WORKFLOW"
          echo "$RUNNER_ARCH"
          echo "$RUNNER_DEBUG"
          echo "$RUNNER_TOOL_CACHE"
        
        


